import {notFound} from 'next/navigation'
import Link from 'next/link'
import {db} from '@/lib/db'

export default async function AppPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params
 const app=await db.application.findUnique({where:{slug},include:{publisher:true,categories:{include:{category:true}},versions:{orderBy:{releaseDate:'desc'}}}})
 if(!app)return notFound()
 const current=app.versions.find(v=>v.current)??app.versions[0]
 return <main className="section"><div className="container"><div className="detail"><div><div className="detailHero"><div className="icon">{app.name.slice(0,1)}</div><div><h1>{app.name}</h1><div className="muted">{app.publisher.name} · {app.license.replace('_',' ')} {app.openSource?'· Open source':''}</div></div></div><p style={{fontSize:18,lineHeight:1.6}}>{app.description}</p><div className="card"><div className="row"><span>Current version</span><strong>{current?.version??'Not published'}</strong></div><div className="row"><span>Latest release</span><span>{current?new Date(current.releaseDate).toLocaleDateString():'Pending verification'}</span></div><div className="row"><span>Architecture</span><span>{current?.architecture??'Multiple'}</span></div><div className="row"><span>Platform</span><span>{current?.platform?.replace('_',' ')??'Windows'}</span></div><div className="row"><span>Source</span><span>{current?.verified?'Official publisher verified':'Publisher source pending verification'}</span></div></div><section className="section" style={{paddingBottom:0}}><h2>Security</h2><p className="muted">AppNest only labels a version verified after its recorded checksum and publisher signature checks pass. This page never invents a security status.</p><div className="notice">{current?.verified?'✓ Verified metadata for this release.':'Verification pending. Download actions remain limited until an administrator verifies the release.'}</div></section></div><aside><div className="card"><Link className="btn primary" style={{display:'block',textAlign:'center'}} href={app.sourceUrl??app.websiteUrl}>Visit official source</Link><Link className="btn secondary" style={{display:'block',textAlign:'center',marginTop:10}} href={'/builder?apps='+app.id}>Add to Installer</Link><a className="btn ghost" style={{display:'block',textAlign:'center',marginTop:10}} href={app.websiteUrl} target="_blank" rel="noreferrer">Publisher website</a></div><div className="card" style={{marginTop:14}}><strong>Categories</strong>{app.categories.map(c=><div className="pill" style={{display:'inline-block',margin:'8px 5px 0 0'}} key={c.category.id}>{c.category.name}</div>)}</div></aside></div></div></main>
}
